<%@ Page Title="" Language="C#" MasterPageFile="~/Doctor/doctormaster.Master" AutoEventWireup="true" CodeBehind="PendingAppointment.aspx.cs" Inherits="doctor.pendingappointment" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<title>Pending Appointments</title>
</asp:Content>



<asp:Content ID="Content2" ContentPlaceHolderID="Cp3" runat="server">

    <!------------------Styling------------------>
    <link rel="stylesheet" href="/assets/css/grid-view.css"/>


     <h1><strong style="margin:25%">Pending Appointments</strong></h1>
    <br /><br />
    <div style="margin-left:300px">



     <asp:GridView ID="pendingappointments" class="GridView-d"
        runat="server"
        AutoGenerateSelectButton="True" 
         AutoGenerateDeleteButton="True"
           EnableViewState="False"
          OnRowCommand="update_appointment"
          OnRowDeleting="Delete_appointment" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical"
         >
         <AlternatingRowStyle BackColor="White" />
         <FooterStyle BackColor="#CCCC99" />
         <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
         <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
         <RowStyle BackColor="#F7F7DE" />
         <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
         <SortedAscendingCellStyle BackColor="#FBFBF2" />
         <SortedAscendingHeaderStyle BackColor="#848384" />
         <SortedDescendingCellStyle BackColor="#EAEAD3" />
         <SortedDescendingHeaderStyle BackColor="#575357" />
        </asp:GridView>
 </div>
</asp:Content>
